In [122]:
import warnings
warnings.filterwarnings('ignore')

In [123]:
import pandas as pd
import requests

requisicao = requests.get("https://pt.wikipedia.org/wiki/Campeonato_Brasileiro_de_Futebol_de_2023_-_S%C3%A9rie_A")

tabelas = pd.read_html(requisicao.text)

# for tabela in tabelas:
#    display(tabela) #visualizar todas as tabelas da página

tabela_classificacao = tabelas[6]
tabela_jogos = tabelas[7]
display(tabela_classificacao)
display(tabela_jogos)

,Pos,Equipevde,Pts,J,V,E,D,GP,GC,SG,Classificação ou descenso
0,1,Palmeiras (T),62,34,18,8,8,56,30,+26,Fase de grupos da Copa Libertadores de 2024
1,2,Botafogo (T),61,34,18,7,9,55,32,+23,Fase de grupos da Copa Libertadores de 2024
2,3,Flamengo (X),60,34,17,9,8,51,37,+14,Fase de grupos da Copa Libertadores de 2024
3,4,Grêmio (X),59,34,18,5,11,57,50,+7,Fase de grupos da Copa Libertadores de 2024
4,5,Red Bull Bragantino (X),59,34,16,11,7,46,30,+16,Segunda fase da Copa Libertadores de 2024
5,6,Atlético Mineiro (X),57,34,16,9,9,43,27,+16,Segunda fase da Copa Libertadores de 2024
6,7,Fluminense (Q),53,35,15,8,12,46,43,+3,Fase de grupos da Copa Libertadores de 2024[a]
7,8,Athletico Paranaense,52,35,13,13,9,47,39,+8,Fase de grupos da Copa Sul-Americana de 2024
8,9,Cuiabá,47,34,13,8,13,36,35,+1,Fase de grupos da Copa Sul-Americana de 2024
9,10,São Paulo (Q),46,34,12,10,12,37,36,+1,Fase de grupos da Copa Libertadores de 2024[b]
10,11,Fortaleza,44,34,12,8,14,38,40,−2,Fase de grupos da Copa Sul-Americana de 2024
11,12,Corinthians,44,35,10,14,11,40,44,−4,Fase de grupos da Copa Sul-Americana de 2024
12,13,Internacional,43,34,11,10,13,38,43,−5,Fase de grupos da Copa Sul-Americana de 2024
13,14,Vasco da Gama,42,35,11,9,15,37,45,−8,Fase de grupos da Copa Sul-Americana de 2024
14,15,Santos,42,34,11,9,14,37,55,−18,NaN
15,16,Bahia,41,35,11,8,16,44,48,−4,NaN
16,17,Cruzeiro,41,34,10,11,13,32,30,+2,Rebaixados à Série B de 2024
17,18,Goiás,35,34,8,11,15,34,49,−15,Rebaixados à Série B de 2024
18,19,Coritiba (R),29,35,8,5,22,40,69,−29,Rebaixados à Série B de 2024
19,20,América Mineiro (R),21,34,4,9,21,39,71,−32,Rebaixados à Série B de 2024

,Casa \ Fora,AMM,ATP,ATM,BAH,BOT,COR,CTB,CRU,CUI,...,FLU,FOR,GOI,GRE,INT,PAL,RBB,SAN,SPA,VAS
0,América Mineiro,—,2–2,1–1,NaN,1–2,2–0,0–3,0–4,1–2,...,0–3,2–1,0–1,3–4,1–2,1–4,0–2,2–0,2–1,0–1
1,Athletico Paranaense,3–2,—,1–1,2–0,1–0,1–0,3–2,3–3,2–0,...,2–2,1–1,2–0,1–2,2–1,2–2,1–1,NaN,1–1,0–0
2,Atlético Mineiro,2–2,2–1,—,1–0,1–0,0–1,1–2,0–1,1–0,...,2–0,3–1,2–1,NaN,2–0,1–1,1–1,2–0,NaN,1–2
3,Bahia,3–1,1–1,NaN,—,1–2,0–0,3–1,2–2,0–3,...,1–0,2–0,1–1,1–2,1–0,1–0,4–0,1–2,NaN,1–1
4,Botafogo,2–0,1–1,2–0,3–0,—,3–0,4–1,NaN,0–1,...,1–0,2–0,1–1,3–4,3–1,3–4,2–0,a,2–1,2–0
5,Corinthians,1–1,1–0,1–1,1–5,1–0,—,3–1,2–1,1–1,...,2–0,1–1,1–1,4–4,a,0–0,0–1,1–1,1–1,3–1
6,Coritiba,3–1,2–0,1–2,2–4,NaN,NaN,—,1–0,0–3,...,2–0,0–3,0–1,1–2,0–1,0–2,0–1,0–0,1–1,0–0
7,Cruzeiro,1–1,NaN,0–1,3–0,0–0,1–1,0–0,—,0–1,...,0–2,0–1,0–1,1–0,1–2,a,0–0,2–1,1–0,2–2
8,Cuiabá,2–2,NaN,0–4,1–1,0–1,0–1,1–1,0–0,—,...,3–0,2–1,1–1,1–2,NaN,0–2,1–1,3–0,2–1,0–2
9,Flamengo,1–1,0–3,a,1–0,2–3,1–0,3–0,1–1,NaN,...,1–1,2–0,2–0,3–0,0–0,3–0,1–0,1–2,1–1,1–0
10,Fluminense,3–1,2–0,1–1,2–1,0–2,3–3,2–1,1–0,2–0,...,—,1–0,5–3,a,2–0,2–1,2–1,1–0,1–0,1–1
11,Fortaleza,3–2,1–0,2–1,0–0,2–2,2–1,3–1,0–1,0–1,...,4–2,—,NaN,1–1,1–1,NaN,0–3,4–0,0–0,2–0
12,Goiás,NaN,1–1,0–0,4–6,2–1,3–1,1–2,NaN,0–1,...,2–2,1–0,—,1–1,0–0,0–5,0–2,0–1,2–0,1–1
13,Grêmio,3–1,1–2,1–0,1–0,0–2,0–1,5–1,3–0,2–0,...,2–1,0–0,NaN,—,3–1,1–0,3–3,1–0,2–1,NaN
14,Internacional,1–1,0–2,0–2,2–0,NaN,2–2,3–4,0–0,1–2,...,0–0,0–1,1–0,3–2,—,0–0,NaN,7–1,2–1,2–1
15,Palmeiras,NaN,1–0,0–2,1–0,0–1,2–1,3–1,1–0,2–1,...,a,3–1,1–0,4–1,3–0,—,1–1,1–2,5–0,1–0
16,Red Bull Bragantino,2–2,2–0,1–2,2–1,2–2,1–0,NaN,0–3,2–0,...,1–0,NaN,2–0,2–0,0–0,2–1,—,2–0,0–0,1–1
17,Santos,3–2,1–1,0–0,3–0,2–2,0–2,2–1,0–3,0–0,...,a,NaN,4–3,2–1,1–1,0–0,1–3,—,0–0,4–1
18,São Paulo,3–0,2–1,0–2,0–0,0–0,2–1,2–1,1–0,NaN,...,1–0,1–2,2–1,3–0,2–0,0–2,1–0,4–1,—,4–2
19,Vasco da Gama,2–1,0–2,1–0,0–1,1–0,a,5–1,0–1,1–0,...,4–2,1–0,0–1,1–0,1–2,2–2,NaN,0–1,0–0,—

In [124]:
nomes_times = list(tabela_jogos["Casa \ Fora"])
nomes_abreviados = list(tabela_jogos.columns)
nomes_abreviados.pop(0)

# criando dicionário para mesclar os nomes com as abreviações

de_abv_para_nomes = dict(zip(nomes_abreviados, nomes_times)) 
print(de_abv_para_nomes)

{'AMM': 'América Mineiro', 'ATP': 'Athletico Paranaense', 'ATM': 'Atlético Mineiro', 'BAH': 'Bahia', 'BOT': 'Botafogo', 'COR': 'Corinthians', 'CTB': 'Coritiba', 'CRU': 'Cruzeiro', 'CUI': 'Cuiabá', 'FLA': 'Flamengo', 'FLU': 'Fluminense', 'FOR': 'Fortaleza', 'GOI': 'Goiás', 'GRE': 'Grêmio', 'INT': 'Internacional', 'PAL': 'Palmeiras', 'RBB': 'Red Bull Bragantino', 'SAN': 'Santos', 'SPA': 'São Paulo', 'VAS': 'Vasco da Gama'}

Formatando tabela de acordo com os nomes

In [125]:
# define a coluna "Casa \ Fora" como o índice do DataFrame tabela_jogos
tabela_jogos_formatada = tabela_jogos.set_index("Casa \ Fora") # a coluna não será mais tratada como uma coluna regular mas sim como o índice das linhas do DataFrame

tabela_jogos_formatada = tabela_jogos_formatada.unstack().reset_index() # reorganiza a visualização das colunas
tabela_jogos_formatada = tabela_jogos_formatada.rename(columns={"level_0": "Fora", "Casa \ Fora": "Casa", 0:"Resultado"}) # troca o nome das colunas

# função para trocar as abreviações pelos nomes dos times
def ajustar_abv_time(Linha):
    abv = Linha["Fora"]
    nome = de_abv_para_nomes[abv]
    return nome

tabela_jogos_formatada["Fora"] = tabela_jogos_formatada.apply(ajustar_abv_time, axis=1)

# pega as linhas onde a coluna Fora for diferente da coluna Casa
tabela_jogos_formatada = tabela_jogos_formatada[tabela_jogos_formatada["Fora"]!=tabela_jogos_formatada["Casa"]]
display(tabela_jogos_formatada)

                Fora                  Casa Resultado
1    América Mineiro  Athletico Paranaense       3–2
2    América Mineiro      Atlético Mineiro       2–2
3    América Mineiro                 Bahia       3–1
4    América Mineiro              Botafogo       2–0
5    América Mineiro           Corinthians       1–1
..               ...                   ...       ...
394    Vasco da Gama         Internacional       2–1
395    Vasco da Gama             Palmeiras       1–0
396    Vasco da Gama   Red Bull Bragantino       1–1
397    Vasco da Gama                Santos       4–1
398    Vasco da Gama             São Paulo       4–2

[380 rows x 3 columns]

In [126]:
# separando as tabelas entre jogos que aconteceram e jogos que ainda vão acontecer

tabela_jogos_formatada["Resultado"] = tabela_jogos_formatada["Resultado"].fillna("a jogar") # add valor "a jogar" nas colunas sem valor
tabela_jogos_realizados = tabela_jogos_formatada[tabela_jogos_formatada["Resultado"].str.contains("–")] # pega as linhas com a coluna que possui resultados separados por "-"
display(tabela_jogos_realizados)
tabela_jogos_faltantes = tabela_jogos_formatada[~tabela_jogos_formatada["Resultado"].str.contains("–")] # "~" retorna o valor contrário 
tabela_jogos_faltantes = tabela_jogos_faltantes.drop(columns=["Resultado"]) # retira a coluna "resultaoo"
display(tabela_jogos_faltantes)

                Fora                  Casa Resultado
1    América Mineiro  Athletico Paranaense       3–2
2    América Mineiro      Atlético Mineiro       2–2
3    América Mineiro                 Bahia       3–1
4    América Mineiro              Botafogo       2–0
5    América Mineiro           Corinthians       1–1
..               ...                   ...       ...
394    Vasco da Gama         Internacional       2–1
395    Vasco da Gama             Palmeiras       1–0
396    Vasco da Gama   Red Bull Bragantino       1–1
397    Vasco da Gama                Santos       4–1
398    Vasco da Gama             São Paulo       4–2

[343 rows x 3 columns]

                     Fora                  Casa
12        América Mineiro                 Goiás
15        América Mineiro             Palmeiras
27   Athletico Paranaense              Cruzeiro
28   Athletico Paranaense                Cuiabá
43       Atlético Mineiro                 Bahia
49       Atlético Mineiro              Flamengo
60                  Bahia       América Mineiro
86               Botafogo              Coritiba
94               Botafogo         Internacional
106           Corinthians              Coritiba
119           Corinthians         Vasco da Gama
136              Coritiba   Red Bull Bragantino
144              Cruzeiro              Botafogo
152              Cruzeiro                 Goiás
169                Cuiabá              Flamengo
178                Cuiabá             São Paulo
180              Flamengo       América Mineiro
198              Flamengo             São Paulo
215            Fluminense             Palmeiras
217            Fluminense                Santos
236             Fortaleza   Red Bull Bragantino
237             Fortaleza                Santos
251                 Goiás             Fortaleza
253                 Goiás                Grêmio
262                Grêmio      Atlético Mineiro
270                Grêmio            Fluminense
285         Internacional           Corinthians
288         Internacional                Cuiabá
307             Palmeiras              Cruzeiro
311             Palmeiras             Fortaleza
334   Red Bull Bragantino         Internacional
339   Red Bull Bragantino         Vasco da Gama
341                Santos  Athletico Paranaense
344                Santos              Botafogo
362             São Paulo      Atlético Mineiro
363             São Paulo                 Bahia
393         Vasco da Gama                Grêmio

Para fazer a previsão, vamos utilizar os seguintes indicadores:
- média de gols dentro de casa
- média de gols fora de casa
- média de gols sofridos dentro de casa
- média de gols sofridos fora de casa

In [127]:

# separando as colunas de gols fora e gols casa
tabela_jogos_realizados[["gols_casa", "gols_fora"]] = tabela_jogos_realizados["Resultado"].str.split("–", expand=True)
tabela_jogos_realizados = tabela_jogos_realizados.drop(columns=["Resultado"])
tabela_jogos_realizados["gols_casa"] = tabela_jogos_realizados["gols_casa"].astype(int)
tabela_jogos_realizados["gols_fora"] = tabela_jogos_realizados["gols_fora"].astype(int)
display(tabela_jogos_realizados)

media_gols_casa = tabela_jogos_realizados.groupby("Casa").mean(numeric_only=True) # transforma as colunas de gols em inteiros

# calculando média de gols dentro de casa
media_gols_casa = media_gols_casa.rename(columns={"gols_casa": "gols_feitos_casa", "gols_fora": "gols_sofridos_casa"})
display(media_gols_casa)

# calculando média de gols fora
media_gols_fora = tabela_jogos_realizados.groupby("Fora").mean(numeric_only=True)
media_gols_fora = media_gols_fora.rename(columns={"gols_casa": "gols_sofridos_fora", "gols_fora": "gols_feitos_fora"}) # renomeia as colunas
display(media_gols_fora)

                Fora                  Casa  gols_casa  gols_fora
1    América Mineiro  Athletico Paranaense          3          2
2    América Mineiro      Atlético Mineiro          2          2
3    América Mineiro                 Bahia          3          1
4    América Mineiro              Botafogo          2          0
5    América Mineiro           Corinthians          1          1
..               ...                   ...        ...        ...
394    Vasco da Gama         Internacional          2          1
395    Vasco da Gama             Palmeiras          1          0
396    Vasco da Gama   Red Bull Bragantino          1          1
397    Vasco da Gama                Santos          4          1
398    Vasco da Gama             São Paulo          4          2

[343 rows x 4 columns]

                      gols_feitos_casa  gols_sofridos_casa
Casa
América Mineiro               1.058824            1.941176
Athletico Paranaense          1.666667            1.055556
Atlético Mineiro              1.352941            0.882353
Bahia                         1.470588            1.117647
Botafogo                      2.058824            0.941176
Corinthians                   1.388889            1.166667
Coritiba                      0.882353            1.411765
Cruzeiro                      0.705882            0.882353
Cuiabá                        1.176471            1.176471
Flamengo                      1.411765            0.705882
Fluminense                    1.722222            0.833333
Fortaleza                     1.470588            1.058824
Goiás                         1.058824            1.411765
Grêmio                        1.823529            0.882353
Internacional                 1.529412            1.176471
Palmeiras                     1.764706            0.705882
Red Bull Bragantino           1.529412            0.705882
Santos                        1.470588            1.352941
São Paulo                     1.647059            0.764706
Vasco da Gama                 1.176471            1.058824

                      gols_sofridos_fora  gols_feitos_fora
Fora
América Mineiro                 2.235294          1.235294
Athletico Paranaense            1.176471          1.000000
Atlético Mineiro                0.705882          1.176471
Bahia                           1.611111          1.055556
Botafogo                        0.941176          1.176471
Corinthians                     1.352941          0.882353
Coritiba                        2.444444          1.333333
Cruzeiro                        0.882353          1.176471
Cuiabá                          0.882353          0.941176
Flamengo                        1.470588          1.588235
Fluminense                      1.647059          0.882353
Fortaleza                       1.294118          0.764706
Goiás                           1.470588          0.941176
Grêmio                          2.058824          1.529412
Internacional                   1.352941          0.705882
Palmeiras                       1.058824          1.529412
Red Bull Bragantino             1.058824          1.176471
Santos                          1.882353          0.705882
São Paulo                       1.352941          0.529412
Vasco da Gama                   1.444444          0.888889

In [128]:
# mesclando as duas tabelas

tabela_estatisticas = media_gols_casa.merge(media_gols_fora, left_index=True, right_index=True) 
tabela_estatisticas = tabela_estatisticas.reset_index()
tabela_estatisticas = tabela_estatisticas.rename(columns={"Casa": "time"})
display(tabela_estatisticas)

,time,gols_feitos_casa,gols_sofridos_casa,gols_sofridos_fora,gols_feitos_fora
0,América Mineiro,1.058824,1.941176,2.235294,1.235294
1,Athletico Paranaense,1.666667,1.055556,1.176471,1.000000
2,Atlético Mineiro,1.352941,0.882353,0.705882,1.176471
3,Bahia,1.470588,1.117647,1.611111,1.055556
4,Botafogo,2.058824,0.941176,0.941176,1.176471
5,Corinthians,1.388889,1.166667,1.352941,0.882353
6,Coritiba,0.882353,1.411765,2.444444,1.333333
7,Cruzeiro,0.705882,0.882353,0.882353,1.176471
8,Cuiabá,1.176471,1.176471,0.882353,0.941176
9,Flamengo,1.411765,0.705882,1.470588,1.588235
10,Fluminense,1.722222,0.833333,1.647059,0.882353
11,Fortaleza,1.470588,1.058824,1.294118,0.764706
12,Goiás,1.058824,1.411765,1.470588,0.941176
13,Grêmio,1.823529,0.882353,2.058824,1.529412
14,Internacional,1.529412,1.176471,1.352941,0.705882
15,Palmeiras,1.764706,0.705882,1.058824,1.529412
16,Red Bull Bragantino,1.529412,0.705882,1.058824,1.176471
17,Santos,1.470588,1.352941,1.882353,0.705882
18,São Paulo,1.647059,0.764706,1.352941,0.529412
19,Vasco da Gama,1.176471,1.058824,1.444444,0.888889

Cálculo de Valor Esperado
- trabalhando com as probabilidades

# Distribuição de Poisson

Modelo estatístico usado para descrever a frequência com que um evento específico ocorre em um intervalo de tempo ou espaço, dado um conhecimento prévio da média de ocorrências desse evento.
- Parâmetro (lambda)
- a Distribuição de Poisson, o parâmetro λ e o Python podem ser explorados através da biblioteca scipy.stats do Python, que oferece funcionalidades para trabalhar com distribuições estatísticas, incluindo a Distribuição de Poisson
- em Python, podemos utilizar a distribuição de Poisson por meio da scipy.stats.poisson
- ideal para modelar diferentes situações onde a média de ocorrências de um evento é diferente

In [129]:
from scipy.stats import poisson

# função para calcular a probabilidade do time ganhar/perder/empate partir das medias

def calcular_pontuacao_esperada(linha):
    time_casa = linha["Casa"]
    time_fora = linha["Fora"]

    # qual a média de gols que o time da casa faz contra o time de fora 
    lambda_casa = (tabela_estatisticas.loc[tabela_estatisticas["time"]==time_casa, "gols_feitos_casa"].iloc[0] 
                * tabela_estatisticas.loc[tabela_estatisticas["time"]==time_fora, "gols_sofridos_fora"].iloc[0])
    # média de gols time da casa * média de gols sofridos pelo time de fora - jogando fora


    # média de gols que o time de fora faz fora de casa * media de gols que o time da casa sofre dentro de casa
    lambda_fora =  (tabela_estatisticas.loc[tabela_estatisticas["time"]==time_fora, "gols_feitos_fora"].iloc[0] 
                    * tabela_estatisticas.loc[tabela_estatisticas["time"]==time_casa, "gols_sofridos_casa"].iloc[0])



# probabilidade de vitória em casa, probabilidade de empate, probabilidade de vitória fora de casa
    pv_casa = 0
    p_empate = 0
    pv_fora = 0

    for gols_casa in range(8):
        for gols_fora in range(8):
            probabilidade_resultado = poisson.pmf(gols_casa, lambda_casa) * poisson.pmf(gols_fora, lambda_fora)
            if gols_casa == gols_fora:
                p_empate += probabilidade_resultado
            elif gols_casa > gols_fora:
                pv_casa += probabilidade_resultado
            elif gols_casa < gols_fora:
                pv_fora += probabilidade_resultado

    # print(pv_casa)
    # print(p_empate)
    # print(pv_fora)

    ve_casa = pv_casa * 3 + p_empate
    ve_fora = pv_fora * 3 + p_empate
    linha["pontos_casa"] = ve_casa
    linha["pontos_fora"] = ve_fora
    return linha

In [130]:
tabela_jogos_faltantes = tabela_jogos_faltantes.apply(calcular_pontuacao_esperada, axis=1)
display(tabela_jogos_faltantes)

                     Fora                  Casa  pontos_casa  pontos_fora
12        América Mineiro                 Goiás     1.744481     1.049207
15        América Mineiro             Palmeiras     2.595239     0.189743
27   Athletico Paranaense              Cruzeiro     1.287204     1.373984
28   Athletico Paranaense                Cuiabá     1.514050     1.221000
43       Atlético Mineiro                 Bahia     1.159271     1.563992
49       Atlético Mineiro              Flamengo     1.473014     1.202679
60                  Bahia       América Mineiro     1.189456     1.594079
86               Botafogo              Coritiba     0.801446     1.954581
94               Botafogo         Internacional     1.411394     1.336443
106           Corinthians              Coritiba     1.325465     1.400426
119           Corinthians         Vasco da Gama     1.832944     0.915119
136              Coritiba   Red Bull Bragantino     2.564684     0.239341
144              Cruzeiro              Botafogo     1.847315     0.920898
152              Cruzeiro                 Goiás     0.878222     1.876844
169                Cuiabá              Flamengo     1.808212     0.893215
178                Cuiabá             São Paulo     1.908563     0.823122
180              Flamengo       América Mineiro     0.651753     2.154017
198              Flamengo             São Paulo     2.092654     0.713349
215            Fluminense             Palmeiras     2.588109     0.270013
217            Fluminense                Santos     2.105466     0.701259
236             Fortaleza   Red Bull Bragantino     2.339365     0.465070
237             Fortaleza                Santos     1.948382     0.827771
251                 Goiás             Fortaleza     2.110673     0.687137
253                 Goiás                Grêmio     2.420174     0.416899
262                Grêmio      Atlético Mineiro     2.162759     0.650528
270                Grêmio            Fluminense     2.406304     0.394504
285         Internacional           Corinthians     2.085140     0.694137
288         Internacional                Cuiabá     1.911553     0.836720
307             Palmeiras              Cruzeiro     0.903253     1.814789
311             Palmeiras             Fortaleza     1.341740     1.421633
334   Red Bull Bragantino         Internacional     1.533457     1.224369
339   Red Bull Bragantino         Vasco da Gama     1.364558     1.364558
341                Santos  Athletico Paranaense     2.574361     0.274795
344                Santos              Botafogo     2.662062     0.143935
362             São Paulo      Atlético Mineiro     2.324127     0.467349
363             São Paulo                 Bahia     2.307037     0.495102
393         Vasco da Gama                Grêmio     2.431319     0.406856

In [131]:
def ajustar_nome_time(linha):
    for nome in nomes_times:
        if nome in linha["Equipevde"]:
            return nome
    
tabela_classificacao["time"] = tabela_classificacao.apply(ajustar_nome_time, axis=1)
tabela_classificacao_atualizada = tabela_classificacao[["time", "Pts"]]
tabela_classificacao_atualizada["Pts"] = tabela_classificacao_atualizada["Pts"].astype(int)

display(tabela_classificacao_atualizada)

                    time  Pts
0              Palmeiras   62
1               Botafogo   61
2               Flamengo   60
3                 Grêmio   59
4    Red Bull Bragantino   59
5       Atlético Mineiro   57
6             Fluminense   53
7   Athletico Paranaense   52
8                 Cuiabá   47
9              São Paulo   46
10             Fortaleza   44
11           Corinthians   44
12         Internacional   43
13         Vasco da Gama   42
14                Santos   42
15                 Bahia   41
16              Cruzeiro   41
17                 Goiás   35
18              Coritiba   29
19       América Mineiro   21

In [132]:
tabela_pontuacao_casa = tabela_jogos_faltantes.groupby("Casa").sum(numeric_only=True)[["pontos_casa"]]
tabela_pontuacao_fora = tabela_jogos_faltantes.groupby("Fora").sum(numeric_only=True)[["pontos_fora"]]
display(tabela_pontuacao_casa)
display(tabela_pontuacao_fora)

                      pontos_casa
Casa
América Mineiro          1.841210
Athletico Paranaense     2.574361
Atlético Mineiro         4.486886
Bahia                    3.466307
Botafogo                 4.509377
Corinthians              2.085140
Coritiba                 2.126911
Cruzeiro                 2.190456
Cuiabá                   3.425603
Flamengo                 3.281226
Fluminense               2.406304
Fortaleza                3.452414
Goiás                    2.622703
Grêmio                   4.851493
Internacional            2.944852
Palmeiras                5.183348
Red Bull Bragantino      4.904050
Santos                   4.053847
São Paulo                4.001217
Vasco da Gama            3.197502

                      pontos_fora
Fora
América Mineiro          1.238950
Athletico Paranaense     2.594983
Atlético Mineiro         2.766670
Bahia                    1.594079
Botafogo                 3.291024
Corinthians              2.315545
Coritiba                 0.239341
Cruzeiro                 2.797742
Cuiabá                   1.716337
Flamengo                 2.867366
Fluminense               0.971272
Fortaleza                1.292841
Goiás                    1.104036
Grêmio                   1.045032
Internacional            1.530857
Palmeiras                3.236422
Red Bull Bragantino      2.588927
Santos                   0.418730
São Paulo                0.962451
Vasco da Gama            0.406856

In [133]:
# atualizando tabela de acordo com o cálculo do valor esperado e ajustando os nomes das linhas

# agrupando e somando as colunas de pontuação 
def atualizar_pontuacao_previsao(linha):
    time = linha["time"]
    pontuacao = int(linha["Pts"]) + float(tabela_pontuacao_casa.loc[time, "pontos_casa"]) + float(tabela_pontuacao_fora.loc[time, "pontos_fora"])
    return pontuacao


tabela_classificacao_atualizada["Pts"] = tabela_classificacao_atualizada.apply(atualizar_pontuacao_previsao, axis=1)
tabela_classificacao_atualizada = tabela_classificacao_atualizada.sort_values(by="Pts", ascending=False) # atualiza as linhas (times) de acordo com a pontuação descrescente
tabela_classificacao_atualizada = tabela_classificacao_atualizada.reset_index(drop=True)
tabela_classificacao_atualizada.index = tabela_classificacao_atualizada.index + 1
display(tabela_classificacao_atualizada)

                    time        Pts
1              Palmeiras  70.419771
2               Botafogo  68.800401
3    Red Bull Bragantino  66.492977
4               Flamengo  66.148591
5                 Grêmio  64.896525
6       Atlético Mineiro  64.253556
7   Athletico Paranaense  57.169344
8             Fluminense  56.377576
9                 Cuiabá  52.141939
10             São Paulo  50.963668
11             Fortaleza  48.745254
12           Corinthians  48.400685
13         Internacional  47.475708
14                Santos  46.472577
15                 Bahia  46.060386
16              Cruzeiro  45.988198
17         Vasco da Gama  45.604358
18                 Goiás  38.726739
19              Coritiba  31.366251
20       América Mineiro  24.080160